#### 矩阵配置 - config.yml ####################################### ############
#
#你好，欢迎使用Matrix反作弊，这是config.yml，用来定义
# 矩阵的全局设置。
#
# - 如果您遇到任何问题，请到我们的官方 Discord
# 求助群：https://discord.gg/pEvY55J
#
# 有用的链接：
# 网站：https://matrix.rip
# 不和谐：https://discord.gg/pEvY55J
# 维基：https://wiki.matrix.rip
# 问题追踪器：https://github.com/jiangdashao/Matrix-Issues/issues
#
# 无论如何，感谢您使用 Matrix 反作弊！ 鉂？
#
################################################# ##################################

# Matrix 是否应该在启动时检查更新？
check_update: false
access_token: '您的密钥'

# 权限缓存刷新间隔（单位：秒，默认：15）
permission_refresh_interval: 10

# 启用 BungeeCord GeyserMC 支持？
# Matrix 支持两种方式运行 GeyserMC：
# 1. Spigot模式：在Spigot中安装GeyserMC/FloodGate，你不需要修改这个设置，Matrix会自动支持
# 2. Bungee Mode：当GeyserMC安装在BungeeCord中时，需要开启该选项，同时在BungeeCord中安装Matrix
#!!! 如果您尚未在 BungeeCord 中安装 GeyserMC，请勿启用此选项
bungee_geysermc_support: false

# 如果有人使用 /matrix kick 被踢，是否会有闪电视觉效果
kick_strike_lightning: true

# 服务器延迟保护
# 当你的服务器滞后时自动禁用一些检查。 这可以防止
# 大多数（但不是全部）误报的发生。
tps_protection:
  # Enable this feature?
  enable: true

# 触发保护所需的最低 TPS
  min_tps: 18.5

# 滞后峰值阈值（毫秒）
   # 如果服务器在一定时间内没有响应，则关闭检查
  lag_threshold: 1000

# 记录违规（默认值：true）
# 将所有违规记录到文件中。 文件可以在 /plugins/Matrix/logs 中找到
# 警告：如果您使用的是 BungeeCord，我建议设置
# 这为假。 这将防止无用的日志文件
# 被存储并耗尽宝贵的磁盘空间。
log_file: true

# 删除过期日志文件（天）
# 如果日志文件存储超过指定天数，则日志文件将被删除
# 您可以将其设置为 `-1` 以禁用此功能
delete_time: 40

# 拒绝绕过权限（默认值：false）
# 通过将此选项设置为 TRUE，您将强制 Matrix 检查每个人
# 在服务器上，包括具有操作员身份的任何人。 通过设置这个
# 选项为 TRUE，您可以运行必要的测试而无需删除
# 你的运营商状态。
disable_bypass_permission: false

##重新登录时间
# 玩家被踢后多久可以登录（秒）
# 另外，你可以设置 -1 来禁用这个功能
relog_time: -1

# 禁用组件
# 您可以在此处禁用特定的子检查，而不是禁用整个
# 检查，可以在详细消息的末尾找到组件名称
# 示例：如果你在打击中添加“speed.web”，快速网络检查将
#被禁用
disabled_components:
  - 'delay.inv'
  - 'bp.timer'
  - 'bp.pe'
  - 'inv.totem'
  - 'bp.freecam'
  - 'hb.mis'
  - 'ely.re'
  - 'vel.ana'
  - 'vel.expect'
  - 'vel.vet'
  - 'ka.abt.ses'
  - 'ka.abt.acl'
  - 'ka.abt.ses'
  - 'ka.flaw.d'
  - 'jesus.flt'
  - 'jesus.ver'
  - 'jesus.eh'
  - 'jesus.p9'
  - 'move.gf' 
  - 'move.blk.pkt'
  - 'move.invmove'
  - 'move.strafe'
#  - 'move.riptide'
  - 'move.tp' 
  - 'move.vert'
  - 'move.hor'
  - 'move.webacel'
#  - 'sfd.place.c'
#  - 'sfd.place.b'
  - 'sfd.place.t'
  - 'ka.critical.hop'
  - 'interact.vis'
  - 'move.sprint'

# 自定义 VL 权重（格式：组件：新的 vl 权重）
custom_vl_weight:
  - 'sfd.twr:2'
  - 'ka.strafe:4'
# 虚假的反作弊命令
# Matrix 是否应该注册一些虚假的反作弊命令？
fake_anticheat:
  aac: true
  spartan: true